sudo: required

language: elixir

elixir: '1.6.0'
otp_release: '20.0'

services:
  - docker

before_install:
- docker pull rabbitmq:3.7.7-management-alpine
- docker run -d -p 5672:5672 rabbitmq:3.7.7-management-alpine

script:
  - mix test