sudo: required

language: elixir

elixir:
  - '1.6.4'
  - '1.7.3'
otp_release:
  - '20.0'
  - '21.1'

matrix:
  # FIXME: Travis doesn't seem to support this combination yet...
  exclude:
    - elixir: '1.6.4'
      otp_release: '21.1'

services:
  - docker

before_install:
- docker pull rabbitmq:3.7.7-management-alpine
- docker run -d -p 5672:5672 rabbitmq:3.7.7-management-alpine

script:
  - mix test
