sudo: required

language: elixir

elixir: '1.5.2'
otp_release: '19.0'

services:
  - docker

before_install:
- docker pull rabbitmq:3.7.7-management-alpine
- docker run -p 5672:5672 rabbitmq:3.7.7-management-alpine

script:
  - mix test